name: FlowForge Cloud Change Requests
description: Used to request any configuration changes to either Staging or Production environments of FlowForge Cloud
body:
- type: checkboxes
  attributes:
    label: Environment
    options:
      - label: Staging
      - label: Production
 - type: input
   attributes:
     label: Due Date
 - type: textarea
   attributes:
     label: Change Description
 - type: textarea
   attributes:
     label: Validation Steps
     value: |
       - [ ] ...
       - [ ] ...
       - [ ] ...
       
