name: Release Published
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MAINTENANCE_SYNC_TOKEN }}
          fetch-depth: 0
      - name: Log github.ref
        if: ${{ endsWith(github.ref, '.0') }}
        shell: bash
        run: |
          git checkout maintenance
          git reset --hard origin/main
          git push --force origin maintenance

